### ISSUE TITLE
Solve doesn't work with certain Polynomials

### ISSUE THREAD

**Issue by weakit** [mathics/Mathics#801] opened 2020-05-05 16:04 UTC
For example, `Solve[x^5 + 2 x + 1 == 0, x]` results to this:

```
Traceback (most recent call last):
  File "/opt/pypy/lib-python/3/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/pypy/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/main.py", line 299, in <module>
    main()
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/main.py", line 286, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/evaluation.py", line 286, in evaluate
    result = run_with_timeout_and_stack(evaluate, timeout)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/evaluation.py", line 93, in run_with_timeout_and_stack
    return request()
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/evaluation.py", line 263, in evaluate
    result = query.evaluate(self)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/expression.py", line 841, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/expression.py", line 963, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/rules.py", line 63, in apply
    yield_match, expression, {}, evaluation, fully=fully)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 203, in match
    yield_head, expression.get_head(), vars, evaluation)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 132, in match
    yield_func(vars, None)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 195, in yield_head
    yield_choice, expression, attributes, head_vars)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 318, in get_pre_choices
    yield_func(vars)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 184, in yield_choice
    wrap_oneid=expression.get_head_name() != 'System`MakeBoxes')
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 479, in match_leaf
    include_flattened=include_flattened)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 339, in get_wrappings
    yield_func(items[0])
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 475, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/builtin/patterns.py", line 767, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/builtin/patterns.py", line 952, in match
    yield_func(vars, None)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 467, in match_yield
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 479, in match_leaf
    include_flattened=include_flattened)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 339, in get_wrappings
    yield_func(items[0])
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 475, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/builtin/patterns.py", line 767, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/builtin/patterns.py", line 952, in match
    yield_func(vars, None)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 470, in match_yield
    yield_func(new_vars, items_rest)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/pattern.py", line 459, in leaf_yield
    (rest_expression[0] + items_rest[0], next_rest[1]))
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/rules.py", line 39, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/rules.py", line 124, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/builtin/calculus.py", line 763, in apply
    ) for sol in result))
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/builtin/calculus.py", line 763, in <genexpr>
    ) for sol in result))
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/builtin/calculus.py", line 762, in <genexpr>
    if var_sympy in sol)
  File "/opt/pypy/site-packages/Mathics-1.1.dev0-py3.6.egg/mathics/core/convert.py", line 298, in from_sympy
    .format(expr, str(expr.__class__)))
ValueError: Unknown SymPy expression: CRootOf(_Mathics_User_Global`x**5 + 2*_Mathics_User_Global`x + 1, 0) (instance of <class 'sympy.polys.rootoftools.ComplexRootOf'>)
```

Also, Mathematica usually gives solutions in [Root](https://reference.wolfram.com/language/ref/Root.html), which isn't implemented.

![image](https://user-images.githubusercontent.com/34541656/81087347-3be36700-8f17-11ea-9cd5-0cfa627a7928.png)

**Comment by GarkGarcia** [comment] 2020-08-24 18:07
Apparently this error is caused by the fact that the roots of `x^5 + 2 x + 1 == 0` cannot be expressed as radicals and Mathics doesn't know how to deal with it. See [this comment](https://stackoverflow.com/a/36847486).

**Comment by GarkGarcia** [comment] 2020-08-24 18:23
The fix for this is to deal with `CRootOf` instances in the `from_sympy` method, but I'm not quite sure about what's the right way to do it.

The obvious solution is to compute a numeric approximation of the root using `sympy.N`, but that may lead to a loss in numeric precision if the value is used for other calculations. Apparently that's what Wolfram does too: https://www.wolframalpha.com/input/?i=x%5E5+%2B+2+x+%2B+1+%3D+0.

**Comment by GarkGarcia** [comment] 2020-08-24 18:26
I think the best solution is to create a wrapper for `CRootOf`, that would avoid the loss of precision. I'm not quite sure about how this could be displayed for the user though. @wolfv What do you think?

**Comment by GarkGarcia** [comment] 2020-08-24 18:57
> I think the best solution is to create a wrapper for `CRootOf`, that would avoid the loss of precision. I'm not quite sure about how this could be displayed for the user though. @wolfv What do you think?

We could create a `mathics.core.expression.Number` subclass to wrap the `CRootOf` which implements `__str__` by simply printing the numeric approximation folowed by `'...'` or something like that.

**Comment by weakit** [comment] 2020-08-25 04:19
You could also consider using CRootOf as a wrapper for Wolfram's [Root](https://reference.wolfram.com/language/ref/Root.html), which would be much closer to how Mathematica handles it. It'll also require an implementation of [Slot](https://reference.wolfram.com/language/ref/Slot.html) tho. I don't really remember, but I don't think slot was implemented (completely at least).

**Comment by GarkGarcia** [comment] 2020-08-25 12:10
> You could also consider using CRootOf as a wrapper for Wolfram's [Root](https://reference.wolfram.com/language/ref/Root.html), which would be much closer to how Mathematica handles it. It'll also require an implementation of [Slot](https://reference.wolfram.com/language/ref/Slot.html) tho. I don't really remember, but I don't think slot was implemented (completely at least).

That's an interesting idea. I'm not sure how to much of the Slot functionality is implemented, but for now we could just replace the `#1` with an `x`. I'll work on an implementation for it.

**Comment by GarkGarcia** [comment] 2020-08-25 15:14
See https://github.com/mathics/Mathics/pull/806 for update.

**Comment by GarkGarcia** [comment] 2020-08-28 15:20
Fixed in https://github.com/mathics/Mathics/commit/909052e1309d571652068189ad5645df0e48fc1b.

**Closed by GarkGarcia** 2020-08-28 15:20 UTC
Labels: bug, enhancement
