### ISSUE TITLE
Sphere General::notboxes:

### ISSUE THREAD

**Issue by wuyudi** [mathics/Mathics#1157] opened 2021-02-17 07:27 UTC
In the document,
![image](https://user-images.githubusercontent.com/30024051/108169852-3f597f00-7134-11eb-8ef5-c60e7313858d.png)

This return an error

```mma
Graphics3D[{Yellow, Sphere[{{-1, 0, 0}, {1, 0, 0}, {0, 0, Sqrt[3.]}}, 1]}]
```

```mma
General::notboxes:
Graphics3DBox[List[StyleBox[Graphics[List[EdgeForm[GrayLevel[0]], RGBColor[1, 1, 0], Rectangle[List[0, 0]]], 
Rule[ImageSize, 16]], Rule[ImageSizeMultipliers, List[1, 1]]], Sphere3DBox[List[List[-1, 0, 0], List[1, 0, 0], List[0, 0, 
1.7320508075688772]], 1]], Rule[$OptionSyntax, Ignore], Rule[AspectRatio, Automatic], Rule[Axes, False], 
Rule[AxesStyle, List[]], Rule[Background, Automatic], Rule[BoxRatios, Automatic], Rule[ImageSize, Automatic], 
Rule[LabelStyle, List[]], Rule[Lighting, Automatic], Rule[PlotRange, Automatic], Rule[PlotRangePadding, 
Automatic], Rule[TicksStyle, List[]], Rule[ViewPoint, List[1.3, -2.4, 2.]]] is not a valid box structure.
```

**Comment by rocky** [comment] 2021-03-22 13:49
In the current development source, things work. In the docker image I was getting this, but I just refreshed the [dockerhub docker image](https://hub.docker.com/r/mathicsorg/mathics) and things now work

**Comment by rocky** [comment] 2021-04-05 09:01
Closing because I can't reproduce this.

**Closed by rocky** 2021-04-05 09:01 UTC
