### ISSUE TITLE
Can't compute eigenvalues/eigenvectors of matrix with complex elements

### ISSUE THREAD

**Issue by nan-af** [mathics/Mathics#795] opened 2019-11-26 15:42 UTC
You can follow this link to reproduce the problem:

https://mathics.angusgriffith.com/#cXVlcmllcz1KeSUzRCgoJTVDJTVCSW90YSU1RCkoJTVDJTVCSEJhciU1RCklMkZzcXJ0JTVCMiU1RCkoJTdCJTdCMCUyQy0xJTJDMCU3RCUyQyU3QjElMkMwJTJDLTElN0QlMkMlN0IwJTJDMSUyQzAlN0QlN0QpJnF1ZXJpZXM9TWF0cml4Rm9ybSU1Qkp5JTVEJnF1ZXJpZXM9RWlnZW52YWx1ZXMlNUJKeSU1RCZxdWVyaWVzPUVpZ2VudmVjdG9ycyU1Qkp5JTVEJnF1ZXJpZXM9RWlnZW5zeXN0ZW0lNUJKeSU1RA==

**Comment by GarkGarcia** [comment] 2020-08-24 01:22
This is very curious. I'm trying to understand why is `object.__nonzero__` called in [`linalg.py`](https://github.com/mathics/Mathics/blob/master/mathics/builtin/linalg.py#L999):

```
    System::exception:

    Exception raised: cannot determine truth value of Relational
     
    Traceback (most recent call last):
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/web/views.py", line 120, in query
    result = evaluation.evaluate(expr, timeout=settings.TIMEOUT)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/evaluation.py", line 243, in evaluate
    result = run_with_timeout(evaluate, timeout)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/evaluation.py", line 63, in run_with_timeout
    return request()
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/evaluation.py", line 226, in evaluate
    result = query.evaluate(self)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/expression.py", line 941, in evaluate
    return result.evaluate(evaluation)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/expression.py", line 871, in evaluate
    eval_range(range(len(leaves)))
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/expression.py", line 859, in eval_range
    leaves[index] = leaf.evaluate(evaluation)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/expression.py", line 935, in evaluate
    result = rule.apply(new, evaluation, fully=False)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/rules.py", line 65, in apply
    yield_match, expression, {}, evaluation, fully=fully)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 206, in match
    yield_head, expression.get_head(), vars, evaluation)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 135, in match
    yield_func(vars, None)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 198, in yield_head
    yield_choice, expression, attributes, head_vars)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 321, in get_pre_choices
    yield_func(vars)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 187, in yield_choice
    wrap_oneid=expression.get_head_name() != 'System`MakeBoxes')
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 478, in match_leaf
    include_flattened=include_flattened)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 342, in get_wrappings
    yield_func(items[0])
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 474, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/builtin/patterns.py", line 768, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/builtin/patterns.py", line 953, in match
    yield_func(vars, None)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/pattern.py", line 469, in match_yield
    yield_func(new_vars, items_rest)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/rules.py", line 41, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/core/rules.py", line 126, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/mathics/builtin/linalg.py", line 976, in apply
    eigenvects = sorted(eigenvects, key=lambda val_c_vect: (abs(val_c_vect[0]), -val_c_vect[0]), reverse=True)
     
    File "/home/pablo/.local/lib/python3.6/site-packages/sympy/core/relational.py", line 195, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
     
    TypeError: cannot determine truth value of Relational
```

**Comment by GarkGarcia** [comment] 2020-08-24 14:24
Ok, after hacking a lot with the code that is producing this errors I came to the following conclusions:

For aesthetic reasons, Mathics is trying to sort the eigenvectors by their corresponding eigenvalues, but it encounters two problems when the eigenvalues are complex numbers:

1. Complex numbers are not ordered, so it cannot compare them to do the sorting.
2. It apparently has no understanding that `i` represents `srqt(-1)`. It thinks the letter `i` is an arbitrary variable, just like the letter `x`. For example, typing `i * i` in Mathics' shell yields `i ^2` instead of `- 1`.

To fix this error we would have to establish a convention to sort complex numbers.

**Comment by GarkGarcia** [comment] 2020-08-24 17:08
I've written a fix for the issue in https://github.com/mathics/Mathics/pull/804.

**Comment by GarkGarcia** [comment] 2020-08-24 17:10
> Ok, after hacking a lot with the code that is producing this errors I came to the following conclusions:
> 
> For aesthetic reasons, Mathics is trying to sort the eigenvectors by their corresponding eigenvalues, but it encounters two problems when the eigenvalues are complex numbers:
> 
>     1. Complex numbers are not ordered, so it cannot compare them to do the sorting.
> 
>     2. It apparently has no understanding that `i` represents `srqt(-1)`. It thinks the letter `i` is an arbitrary variable, just like the letter `x`. For example, typing `i * i` in Mathics' shell yields `i ^ 2` instead of `- 1`.
> 
> 
> To fix this error we would have to establish a convention to sort complex numbers.

On regards to issue number 1, apparently this is the intended behaviour. The letter `I` represents `Sqrt[-1]` and `i` represents a free variable such as `x`.

**Comment by GarkGarcia** [comment] 2020-08-26 11:17
This was fixed on https://github.com/mathics/Mathics/commit/39442892de0796bb0757a432aa251e89aa0fb5a1.

**Closed** 2020-08-26 12:15 UTC
Labels: bug
