### ISSUE TITLE
Complex (Square) Roots

### ISSUE THREAD

**Issue by constip** [mathics/Mathics#793] opened 2019-11-14 18:00 UTC
Mathics can not solve roots of complex numbers. It just returns the input.
I believe at least the square root should be easy to implement, considering what else Mathics can do: https://mathepedia.de/Potenzen_und_Wurzeln.html (Sorry for German, look at the formula under "Quadratwurzeln"). Alternatively: https://math.stackexchange.com/questions/44406/how-do-i-get-the-square-root-of-a-complex-number (Caution, some answers only calculate one answer)

**Comment by GarkGarcia** [comment] 2020-08-24 20:45
This is definitively something that should be fixed. I don't really understand why I doesn't work already.

**Comment by GarkGarcia** [comment] 2020-08-28 17:40
I think I see what the issue is. Given a complex number `z`, what does `Sqrt[z]` means? One may say `Sqrt[z]` is a solution to the equation `x^2 - z = 0`. The thing is, since complex number are [algebraically closed](https://en.wikipedia.org/wiki/Algebraically_closed_field), there are precisely two complex solutions to `x^2 - z == 0` (because `Deg[p] == 2` for `p[x_] := x^2 - 2`). 

Real numbers are [ordered](https://en.wikipedia.org/wiki/Ordered_field), so the convention for `Sqrt[y]` (for a positive real number `y`) is to pick the positive solution of `y^2 - x == 0` (it isn't hard to prove a positive solution always exists). Complex numbers are not ordered, so there isn't any convention for `Sqrt`, there are two equally valid solutions.

I curious to know how Mathematica handles this (you mentioned Mathematica computes "complex (square) roots").

**Comment by constip** [comment] 2020-08-28 17:48
Not sure where you think I mentioned this, but you can look at the free version WolframAlpha: https://www.wolframalpha.com/input/?i=sqrt%28i-1%29 It appears they simply choose the one with the smallest angle

**Comment by GarkGarcia** [comment] 2020-08-29 16:39
> It appears they simply choose the one with the smallest angle

I see, makes sense to me. We should definitively try to emulate the behaviour of Mathematica in here (which I assume is the same as WolframAlpha's).

After digging around a bit I came to the conclusion this is not a limitation of Mathics, this is a limitation of SymPy. SymPy is the CAS engine used by Mathics internally (it's a Python library for abstract mathematical computations).

See, `Sqrt[x]` is just syntactic sugar for `x ^ 1/2`, which is syntactic sugar for `Pow[x, 1/2]`, which is a wrapper for `sympy.Pow(x, 1/2)`. Therefore, the behaviour of `Sqrt` is limited to the behaviour of `sympy.Pow`. Unfortunately, it looks like `sympy` is not able to compute complex square roots:

```
>>> from sympy import Pow, Integer, I
>>> Pow(Integer(3),     Integer(1)/Integer(2))
sqrt(3)
>>> Pow(Integer(4),     Integer(1)/Integer(2))
2
>>> Pow(Integer(1) + I, Integer(1)/Integer(2))
sqrt(1 + I)
>>>
```

In my opinion, the most appropriate thing to do is to create a feature request in [`sympy/sympy`](https://github.com/sympy/sympy). Also, note that Mathics is using a quite old version of SymPy (version 1.0, the latest is 1.5), so this feature may have already been implemented by now.

**Comment by GarkGarcia** [comment] 2020-08-31 23:19
As stated in https://github.com/sympy/sympy/issues/20024#issuecomment-683917668, I might be a better idea to leave `Sqrt` as is, since in most cases `Sqrt[z]` is cleaner than it's rectangular representation. However, I believe users should be able to expand `Sqrt[z]` if they wish to do so. @constip Would that work for you?

I have two potential solutions in mind:

1. Something along the lines of `Expand[Sqrt[z]]`, which would expand the complex root to it's rectangular representation.
2. Something along the lines of `Re[Sqrt[z]]+ Im[Sqrt[z]] I`. `Re[x]` would return the real component of  `x` (`Re[1 - I] == 1`) and `Im[x]` would return the imaginary component of `x` (`Im[1 - I] == -1`).

`Expand` is already a builtin, so we'd have to implement a special case for complex square roots. Also, I would be great if we could emulate WolframAlpha's behaviour (expanding `Sqrt[z]` as `r Cos[theta] + r Sin[theta] I` for the appropriate `r` and `theta`). However, there are a couple of problems with this:

1. Mathics would expand `Sin[theta]` and `Cos[theta]` to their radical representation, which would result in much messier output. For example, `3 Cos[Pi / 8] + 3 Sin[Pi / 8] I` would be expanded to `3 I Sqrt[1 / 2 - Sqrt[2] / 4] + 3 Sqrt[1 / 2 + Sqrt[2] / 4]`.
2. SymPy is (apparently) not as competent as WolframAlph on regards to trigonometry. For example, the argument (the angle) of `sqrt(1 + I)` (`Sqrt[1 + I]` in Mathics) is displayed as `atan(sqrt(-sqrt(2) + 2)/sqrt(sqrt(2) + 2))`, instead of `pi/8`. That would make it impractical to format `Sqrt[1 + I]` in Wolfram's trigonometric representation.

**Comment by constip** [comment] 2020-09-01 05:07
I no longer actively use Mathics, so I believe it's best to leave this decision to actively involved members. Though in my opinion the first would be more intuitive.

**Comment by suhr** [comment] 2020-09-01 08:16
Yeah, the first solutions seems to be the most straightforward.

**Comment by axkr** [comment] 2020-09-01 15:29
There is already a `PowerExpand`function:
- https://github.com/mathics/Mathics/blob/1927ada93c5ce2d8cbe731731ab1f55cd5527467/mathics/builtin/algebra.py#L702

**Comment by GarkGarcia** [comment] 2020-09-01 15:36
> There is already a `PowerExpand`function:
> 
>     * https://github.com/mathics/Mathics/blob/1927ada93c5ce2d8cbe731731ab1f55cd5527467/mathics/builtin/algebra.py#L702

I don't think `PowerExpand` works for this:

```
In[1]:= PowerExpand[Sqrt[(3 + 4I) ^ 2]]
Out[1]= Sqrt[-7 + 24 I]
```

**Comment by axkr** [comment] 2020-09-01 15:54
Your example works at least in Mathematica.
- https://reference.wolfram.com/language/ref/PowerExpand.html

**Comment by GarkGarcia** [comment] 2020-09-03 15:04
> but also independent of `PowerExpand` - `Sqrt[-7 + 24 I]` -> `3 + 4*I`

Exactly, this example works in Mathematica because Mathematica expands `Sqrt[-7 + 24 I]` to `3 + 4*I`, not because of `PowerExpand`.

**Comment by GarkGarcia** [comment] 2020-09-03 15:10
The https://github.com/mathics/Mathics/pull/817 PR made it so that the `Re` and `Im` functions expand complex square roots to their rectangular form. Now users are able to expand complex square roots by doing the following:

```
In[1]:= z = Sqrt[1 + I]
Out[1]= Sqrt[1 + I]

In[2]:= Re[z] + Im[z] I
Out[2]= I 2 ^ (1 / 4) Sqrt[1 / 2 - Sqrt[2] / 4] + 2 ^ (1 / 4) Sqrt[1 / 2 + Sqrt[2] / 4]
```

@suhr Would that work for you?

**Comment by suhr** [comment] 2020-09-03 15:15
I guess so, though it's less convenient than a single function.

**Closed** 2020-09-04 12:39 UTC
Labels: enhancement, upstream
