### ISSUE TITLE
Gettting initial page hangs with django 2.2

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#905] opened 2020-09-18 22:02 UTC
Sometimes connecting to http://localhost:8000 works and is slow to load, sometimes it can be fast. Sometimes it hangs. 

I've seen this both on firefox and chrome. Sometimes disabling the cache helps but doesn't always prevent hangs.

Overall reliabllity is worse for me.

**Comment by GarkGarcia** [comment] 2020-09-19 12:56
I'm experiencing the same issue. But I'm not sure what's causing it...

**Comment by rocky** [comment] 2020-09-19 13:06
Can I suggest we keep this as a branch and revert to the old django for now? I have a patch to go between the old and the new.

**Comment by GarkGarcia** [comment] 2020-09-19 14:03
> Can I suggest we keep this as a branch and revert to the old django for now? I have a patch to go between the old and the new.

I'd like to try to fix this before reverting the update. I probably messed something up in https://github.com/mathics/Mathics/commit/c3a01606756ea1b620a8da3640fb4620b469313f#diff-41ddb83d5ff1c0f9a3d1315f5201799eR56 or in https://github.com/mathics/Mathics/commit/c3a01606756ea1b620a8da3640fb4620b469313f#diff-5f49e5dd9dc2ab5cb52fbd4f6407500eR109.

**Comment by GarkGarcia** [comment] 2020-09-19 14:06
I remember that replacing `models.CASCADE` instead of `models.SET_NULL` in https://github.com/mathics/Mathics/commit/c3a01606756ea1b620a8da3640fb4620b469313f#diff-41ddb83d5ff1c0f9a3d1315f5201799eR56 solved the hanging issues we were facing, but it introduced some other errors. I honestly have no idea which one is the most appropriate.

**Comment by GarkGarcia** [comment] 2020-09-19 14:35
As you can see in this `.har` file, the server apparently hangs on some very specific image/js/css files: https://pastebin.com/i6cDHzHr.

You can open the `.har` file by downloading it from pastebin, opening up the Firefox Developer Tool (press `F12`), going to the "Network" tab, clicking the ⚙️ icon on the top-right corner and selecting "Import HAR File".

**Comment by GarkGarcia** [comment] 2020-09-19 14:42
> As you can see in this `.har` file, the server apparently hangs on some very specific image/js/css files: https://pastebin.com/i6cDHzHr.
> 
> You can open the `.har` file by downloading it from pastebin, opening up the Firefox Developer Tool (press `F12`), going to the "Network" tab, clicking the gear icon on the top-right corner and selecting "Import HAR File".

This files shows which resources are requested from the main page, and which ones are causing the page to hang. As you can see, the hang is caused by some `GET` requests. I've tested this multiple times, and the `GET` requested that hang (the server don't bother answering them from some reason) are usually requests for the same resources:

* Three.js
* Detector.js
* Mathjax.js
* message.js
* authentication.js
* Random SVG/PNG files.

**Comment by rocky** [comment] 2020-09-19 15:01
While all of this is interesting, it is irresponsible to have a known broken/buggy master around for any length of time. 

Please revert the change, and keep it in a branch until it is ready to be merged. 

I do not want to make changes that I can't test and on top of buggy code.

**Comment by GarkGarcia** [comment] 2020-09-19 21:56
> While all of this is interesting, it is irresponsible to have a known broken/buggy master around for any length of time.
> 
> Please revert the change, and keep it in a branch until it is ready to be merged.
> 
> I do not want to make changes that I can't test and on top of buggy code.

I'll try fixing this in until Monday. If I can't get it working till then I'll move this to separate branch, is that okay to you?

**Comment by rocky** [comment] 2020-09-19 21:57
Ok. But I am not able to commit until this is resolved.

**Comment by mmatera** [comment] 2020-09-19 23:04
> > While all of this is interesting, it is irresponsible to have a known broken/buggy master around for any length of time.
> > Please revert the change, and keep it in a branch until it is ready to be merged.
> > I do not want to make changes that I can't test and on top of buggy code.
> 
> I'll try fixing this in until Monday. If I can't get it working till then I'll move this to a separate branch, is that okay to you?

@GarkGarcia, I agree with @rocky, the best would be to at least open a testing branch, and investigate over it. The same for the upgrades in any of the basic subsystems (core modules, tests, etc). Doing PRs over buggy code leads to propagate bugs...

**Comment by GarkGarcia** [comment] 2020-09-21 15:43
> > > While all of this is interesting, it is irresponsible to have a known broken/buggy master around for any length of time.
> > > Please revert the change, and keep it in a branch until it is ready to be merged.
> > > I do not want to make changes that I can't test and on top of buggy code.
> > 
> > 
> > I'll try fixing this in until Monday. If I can't get it working till then I'll move this to a separate branch, is that okay to you?
> 
> @GarkGarcia, I agree with @rocky, the best would be to at least open a testing branch, and investigate over it. The same for the upgrades in any of the basic subsystems (core modules, tests, etc). Doing PRs over buggy code leads to propagate bugs...

Fair enough. I wasn't able to work on this in the weekend, so I'll create a separate branch for it and revert the changes.

**Comment by GarkGarcia** [comment] 2020-09-21 16:30
Still, I think we should update to Django 2.2 before 1.1

**Comment by rocky** [comment] 2020-09-21 17:56
That never was at argument. 

It the _way_ this was done. No review, and not working either. And then left in for a while which impacts others.

**Comment by GarkGarcia** [comment] 2020-09-22 00:30
> That never was at argument.
> 
> It the _way_ this was done. No review, and not working either. And then left in for a while which impacts others.

Fair enough. I merged the PR because it passed the tests and it worked locally at first. After the PR was merged I started experiencing the issues you described. I'm sorry for that.

**Closed by GarkGarcia** 2020-09-22 00:30 UTC
Labels: bug
