### ISSUE TITLE
Can't run Mathics on Windows with Python 3.8 installed

### ISSUE THREAD

**Issue by nikolazlatkovic** [mathics/Mathics#798] opened 2020-02-28 16:34 UTC
Hi everyone!

I have installed Mathics on Windows 10 machine with Python 3.8, using `pip install mathics`, and got following error, when I tried to run `mathics`:

    Traceback (most recent call last):
    File "C:\Users\zlaja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\mathics-script.py", line 11, in <module>
        load_entry_point('Mathics==1.0', 'console_scripts', 'mathics')()
    File "C:\Users\zlaja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mathics\main.py", line 242, in main
        definitions = Definitions(add_builtin=True)
    File "C:\Users\zlaja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mathics\core\definitions.py", line 55, in __init__
        from mathics.builtin import modules, contribute
    File "C:\Users\zlaja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mathics\builtin\__init__.py", line 7, in <module>
        from mathics.builtin import (
    File "C:\Users\zlaja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mathics\builtin\structure.py", line 23, in <module>
        from .pympler.asizeof import asizeof as count_bytes
    File "C:\Users\zlaja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mathics\builtin\pympler\asizeof.py", line 217, in <module>
        u = u.encode('unicode-internal')  # see .../Lib/test/test_sys.py
    LookupError: unknown encoding: unicode-internal

After switching back to Python 3.7, error was gone, and Mathics worked correctly.

**Comment by raxod502** [comment] 2020-06-09 15:34
I encounter this problem with Python 3.8 running on Ubuntu 20.04 within a Docker container. This suggests to me that it's 3.8 compatibility which is the problem.

**Comment by GarkGarcia** [comment] 2020-08-24 20:28
I'm not sure what the issue is, but apparently Mathics still used Python 3.6. So I believe it's a compatibility issue indeed.

**Comment by rocky** [comment] 2020-09-08 16:46
@nikolazlatkovic 
> LookupError: unknown encoding: unicode-internal

This was recently fixed in https://github.com/mathics/Mathics/pull/839

**Closed** 2020-09-08 21:16 UTC
