### ISSUE TITLE
bug with Import

### ISSUE THREAD

**Issue by Lillille** [mathics/Mathics#663] opened 2016-12-15 12:48 UTC
The following command

     data = Import["C:\\0000000\\mathematica\\classeur1.csv", "CSV"]

works with MLathematica but not with Mathics under Windows7 a too long set of error to include them

**Comment by sn6uv** [comment] 2016-12-18 20:32
Could you please upload that file, `classeur1.csv` so we can investigate.

**Comment by sn6uv** [comment] 2016-12-18 20:38
Closing as duplicate of #660. Please refrain from opening multiple bugs for this.

**Closed by sn6uv** 2016-12-18 20:38 UTC
Labels: more information needed
